- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: |
      task: DotNetCoreCLI@2
        displayName: 'Build the project'
        inputs:
          command: 'build'
          arguments: '--no-restore --configuration Release'
          projects: '**/*.csproj'